// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb9SpHKefdL37mDTEtSRaXO0gPqTkXneE',
    appId: '1:764263667790:web:8714619e1d8f3b0cf6cb1f',
    messagingSenderId: '764263667790',
    projectId: 'readwithmint',
    authDomain: 'readwithmint.firebaseapp.com',
    storageBucket: 'readwithmint.appspot.com',
    measurementId: 'G-2YKZ60Q2K7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1LGlJHccgVwbLQn-OLGTujAovGY8bAkw',
    appId: '1:764263667790:android:5d6ebc85fde3b1a6f6cb1f',
    messagingSenderId: '764263667790',
    projectId: 'readwithmint',
    storageBucket: 'readwithmint.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLXMzhwkWnc9eSTkUxwO6RAT1DCjfdd5M',
    appId: '1:764263667790:ios:acad76b5b5cc7a56f6cb1f',
    messagingSenderId: '764263667790',
    projectId: 'readwithmint',
    storageBucket: 'readwithmint.appspot.com',
    iosBundleId: 'com.example.readwithmint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLXMzhwkWnc9eSTkUxwO6RAT1DCjfdd5M',
    appId: '1:764263667790:ios:bc56b1d3d3e88c39f6cb1f',
    messagingSenderId: '764263667790',
    projectId: 'readwithmint',
    storageBucket: 'readwithmint.appspot.com',
    iosBundleId: 'com.example.readwithmint.RunnerTests',
  );
}
